urlapp/urls.py
from django.urls import path
from urlapp import views

#Global inbuilt variable name
app_name='urlapp'

urlpatterns=[
    path('',views.index,name='index'),
    path('contact/',views.contact,name='contact'),
    path('relative/',views.relative,name='relative'),
    path('about/',views.about, name='about')
]

urlproj/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('urlapp.urls')),
    path('admin/', admin.site.urls),
]

urlapp/models.py
from django.db import models

# Create your models here.

urlapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    mydict={'insert_me':'i am the devil of my world'}
    return render(request,'index.html',context=mydict)
def contact(request):
    mydict={'insert_me':'i am the devil of my world'}
    return render(request,'contact.html',context=mydict)
def relative(request):
    mydict={'insert_me':'i am the devil of my world'}
    return render(request,'relative.html',context=mydict)
def about(request):
    mydict={'insert_me':'i am the devil of my world'}
    return render(request,'about.html',context=mydict)

templates/about.html
{% extends 'base.html'%}
{% block content %}
<h1>Thid is About page</h1>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://kit.fontawesome.com/9a5c5a0bb3.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar nav-dark bg-dark">
        <div class="container">
            <ul class="nav navbar">
                <li class="nav-items"><a class="nav-links" href="{% url 'urlapp:index'%}">Home</a></li>
                <li class="nav-items"><a class="nav-link" href="{% url 'urlapp:contact'%}">contact</a></li>
                <li class="nav-items"><a class="nav-link" href="{% url 'urlapp:relative'%}">relative</a></li>
                <li class="nav-items"><a class="nav-link" href="{% url 'urlapp:about'%}">About</a></li>
                <li class="nav-item"><a class=nav-link><i class="fa-brands fa-instagram"></i></a></li>
                <li class="nav-item"><a class=nav-link><i class="fa-solid fa-car"></i></a>/li>
                <li class="nav-item"><a class=nav-link><i class="fa-brands fa-spotify"></i></a></li>    
            </ul>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    {{ insert_me | upper}}
    <!-- <a href="{% url 'urlapp:index'%}">Home</a>
    <a href="{% url 'urlapp:contact'%}">Contact</a>
    <a href="{% url 'urlapp:relative'%}">Relative</a> -->
    <!-- <a> <i class="fa-duotone fa-laptop"></i></a>
    <a><i class="fa-solid fa-car"></i></a> -->
</body>
</html>

templates/contact.html
{% extends 'base.html'%}
{% block content %}
<h1>Thid is Contact page</h1>
{{ insert_me | title}}

{% endblock %}

templates/index.html
{% extends 'base.html'%}
{% block content %}
<h1>Thid is index page</h1>
{{ insert_me | upper}}
{% endblock %}

templates/relative.html
{% extends 'base.html'%}
{% block content %}
<h1>Thid is relative page</h1>
{{ insert_me | lower}}
{% endblock %}